etp_web_personnel:
    resource: "@EtpWebPersonnelBundle/Resources/config/routing.yml"
    prefix:   /

etp_web_planning:
    resource: "@EtpWebPlanningBundle/Resources/config/routing.yml"
    prefix:   /

etp_web_vehicule:
    resource: "@EtpWebVehiculeBundle/Resources/config/routing.yml"
    prefix:   /

etp_web_souffrance:
    resource: "@EtpWebSouffranceBundle/Resources/config/routing.yml"
    prefix:   /

etp_web_core:
    resource: "@EtpWebCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

connexion:
    pattern: /connexion
    defaults: { _controller:EtpWebUserBundle:Security:connexion }

login_check:
    pattern: /login_check

logout:
    pattern: /logout