<?php

namespace EtpWeb\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends EntityRepository
{
}
